from __future__ import annotations

from pathlib import Path

import xlsxwriter

from asin_1688_roi.models import CandidateProduct, RoiResult, TargetProduct

TARGET_HEADERS = [
    "ASIN",
    "售价",
    "CPC",
    "Amazon商品名称",
    "1688搜索关键词",
    "材质",
    "功能",
    "结构",
    "销售单元",
    "套装数量",
    "配件数量",
    "产品长cm",
    "产品宽cm",
    "产品高cm",
    "产品重量kg",
    "包装长cm",
    "包装宽cm",
    "包装高cm",
    "包装重量kg",
    "FBA",
    "备注",
]
CANDIDATE_HEADERS = [
    "ASIN",
    "1688搜索关键词",
    "Offer ID",
    "1688商品标题",
    "1688商品链接",
    "商品图片",
    "供应商",
    "店铺链接",
    "省份",
    "城市",
    "页面价格",
    "完整销售单元采购价",
    "起订量",
    "销量",
    "回头率",
    "材质",
    "功能",
    "结构",
    "销售单元",
    "套装数量",
    "配件数量",
    "长cm",
    "宽cm",
    "高cm",
    "详情文本",
    "截图路径",
    "抓取时间",
    "人工有效",
    "人工判断原因",
    "匹配分",
    "匹配状态",
    "剔除/缺口原因",
    "原始JSON",
]
ROI_HEADERS = [
    "ASIN",
    "售价",
    "CPC",
    "汇率",
    "采购成本",
    "物流成本",
    "FBA",
    "Amazon佣金",
    "仓储成本",
    "广告成本",
    "推测真实毛利",
    "真实毛利率",
    "投产比",
    "有效候选数",
    "采购价来源",
    "状态",
]


def _write_table(
    worksheet, headers: list[str], rows: list[list[object]], formats: dict[str, object]
):
    worksheet.freeze_panes(1, 0)
    worksheet.autofilter(0, 0, max(len(rows), 1), len(headers) - 1)
    for col, header in enumerate(headers):
        worksheet.write(0, col, header, formats["header"])
    for row_index, row in enumerate(rows, start=1):
        for col_index, value in enumerate(row):
            fmt = formats["body"]
            if isinstance(value, float):
                fmt = formats["number"]
            worksheet.write(row_index, col_index, value, fmt)
    worksheet.set_row(0, 26)


def write_workbook(
    path: str | Path,
    *,
    targets: list[TargetProduct],
    candidates: list[CandidateProduct],
    results: list[RoiResult],
) -> Path:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    workbook = xlsxwriter.Workbook(output, {"strings_to_formulas": False})
    workbook.set_properties(
        {
            "title": "ASIN 1688 ROI result",
            "author": "asin-1688-roi-tool",
            "comments": "Generated by asin-1688-roi-tool",
        }
    )
    formats = {
        "header": workbook.add_format(
            {
                "bold": True,
                "font_color": "white",
                "bg_color": "#1F4E78",
                "border": 1,
                "align": "center",
                "valign": "vcenter",
            }
        ),
        "body": workbook.add_format({"border": 1, "valign": "top", "text_wrap": True}),
        "number": workbook.add_format({"border": 1, "num_format": "0.00", "valign": "top"}),
        "percent": workbook.add_format({"border": 1, "num_format": "0.00%", "valign": "top"}),
        "note": workbook.add_format({"text_wrap": True, "valign": "top", "bg_color": "#FFF2CC"}),
    }

    roi_ws = workbook.add_worksheet("ROI结果")
    roi_rows: list[list[object]] = []
    for r in results:
        roi_rows.append(
            [
                r.asin,
                r.selling_price_usd,
                r.cpc_usd,
                r.fx_usd_cny,
                r.procurement_cost_cny,
                r.logistics_cost_cny,
                r.fba_fee_usd,
                r.commission_cny,
                r.storage_cost_cny,
                r.ad_cost_cny,
                r.inferred_real_profit_cny,
                r.inferred_real_margin,
                r.roi,
                r.valid_candidate_count,
                r.procurement_source,
                r.status,
            ]
        )
    _write_table(roi_ws, ROI_HEADERS, roi_rows, formats)
    roi_ws.set_column("A:A", 14)
    roi_ws.set_column("B:N", 13)
    roi_ws.set_column("O:O", 45)
    roi_ws.set_column("P:P", 25)
    for row in range(1, len(roi_rows) + 1):
        roi_ws.set_row(row, 22)
        roi_ws.write(row, 11, roi_rows[row - 1][11], formats["percent"])
        roi_ws.write(row, 12, roi_rows[row - 1][12], formats["percent"])

    candidate_ws = workbook.add_worksheet("1688候选")
    candidate_rows = [
        [
            c.asin,
            c.search_keyword,
            c.offer_id,
            c.title,
            c.product_url,
            c.image_url,
            c.supplier,
            c.shop_url,
            c.province,
            c.city,
            c.page_price_text,
            c.comparison_price_cny,
            c.min_order_quantity,
            c.sales_text,
            c.return_rate,
            c.material,
            c.function,
            c.structure,
            c.sales_unit,
            c.pack_quantity,
            c.accessory_quantity,
            c.length_cm,
            c.width_cm,
            c.height_cm,
            c.detail_text,
            c.screenshot_path,
            c.source_timestamp,
            c.manual_valid,
            c.manual_reason,
            c.match_score,
            c.match_status,
            c.rejection_reason,
            c.raw_json[:32000],
        ]
        for c in candidates
    ]
    _write_table(candidate_ws, CANDIDATE_HEADERS, candidate_rows, formats)
    candidate_ws.set_column("A:C", 16)
    candidate_ws.set_column("D:D", 45)
    candidate_ws.set_column("E:F", 42)
    candidate_ws.set_column("G:J", 20)
    candidate_ws.set_column("K:O", 15)
    candidate_ws.set_column("P:S", 18)
    candidate_ws.set_column("T:X", 12)
    candidate_ws.set_column("Y:AG", 30)

    input_ws = workbook.add_worksheet("ASIN输入")
    target_rows = [
        [
            t.asin,
            t.selling_price_usd,
            t.cpc_usd,
            t.amazon_title,
            " | ".join(t.search_keywords),
            t.material,
            t.function,
            t.structure,
            t.sales_unit,
            t.pack_quantity,
            t.accessory_quantity,
            t.length_cm,
            t.width_cm,
            t.height_cm,
            t.product_weight_kg,
            t.package_length_cm,
            t.package_width_cm,
            t.package_height_cm,
            t.package_weight_kg,
            t.fba_fee_usd,
            t.notes,
        ]
        for t in targets
    ]
    _write_table(input_ws, TARGET_HEADERS, target_rows, formats)
    input_ws.set_column("A:A", 14)
    input_ws.set_column("B:C", 11)
    input_ws.set_column("D:E", 38)
    input_ws.set_column("F:I", 20)
    input_ws.set_column("J:T", 12)
    input_ws.set_column("U:U", 30)

    trace_ws = workbook.add_worksheet("来源追溯")
    trace_headers = ["ASIN", "字段", "数值", "来源类型", "来源链接/计算方式", "状态"]
    trace_rows: list[list[object]] = []
    for r in results:
        fx_source_type = "公开汇率 API" if r.fx_source.startswith("https://") else "调用方输入"
        trace_rows.extend(
            [
                [r.asin, "售价", r.selling_price_usd, "用户输入", "ASIN输入表", "已使用"],
                [r.asin, "CPC", r.cpc_usd, "用户输入", "ASIN输入表", "已使用"],
                [r.asin, "汇率", r.fx_usd_cny, fx_source_type, r.fx_source, "已使用"],
                [
                    r.asin,
                    "采购成本",
                    r.procurement_cost_cny,
                    "1688严格同规格",
                    r.procurement_source,
                    "已使用" if r.procurement_cost_cny is not None else "",
                ],
                [
                    r.asin,
                    "物流成本",
                    r.logistics_cost_cny,
                    "公式计算",
                    "四种美西物流渠道取最大值",
                    "已使用" if r.logistics_cost_cny is not None else "",
                ],
                [
                    r.asin,
                    "FBA",
                    r.fba_fee_usd,
                    "用户输入",
                    "ASIN输入表",
                    "已使用" if r.fba_fee_usd is not None else "",
                ],
            ]
        )
    _write_table(trace_ws, trace_headers, trace_rows, formats)
    trace_ws.set_column("A:C", 16)
    trace_ws.set_column("D:F", 35)

    rule_ws = workbook.add_worksheet("参数说明")
    rules = [
        ["规则", "内容"],
        [
            "采购价",
            "仅从匹配状态为“有效-自动/有效-人工确认”的1688候选中，取完整销售单元采购价最高值。",
        ],
        ["严格匹配", "材质、尺寸、功能、结构、销售单元、套装数量、配件数量不得跨规格混算。"],
        ["佣金", "售价人民币 × 15%"],
        ["仓储", "$0.10/件 × USD/CNY"],
        ["广告", "CPC × 广告流量占比20% ÷ 转化率10% × USD/CNY，即 CPC × 2 × 汇率"],
        ["物流", "重量×8.5、体积×1360、重量×10.6、体积×1900，四者取最大值。"],
        ["投产比", "推测真实毛利 ÷（采购成本+物流成本）"],
        ["Cookie安全", "Cookie只应保存在本机，不要提交到GitHub、聊天或共享网盘。"],
    ]
    for r, row in enumerate(rules):
        for c, value in enumerate(row):
            rule_ws.write(r, c, value, formats["header"] if r == 0 else formats["note"])
    rule_ws.set_column("A:A", 18)
    rule_ws.set_column("B:B", 90)
    rule_ws.set_default_row(30)
    workbook.close()
    return output
